# Generated by Django 5.2.5 on 2025-08-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_livro', models.CharField(max_length=150)),
                ('genero_livro', models.CharField(max_length=50)),
                ('ano_publicacao', models.PositiveSmallIntegerField()),
                ('data_cadastro_livro', models.DateTimeField(auto_now_add=True)),
                ('status_livro', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado'), ('reservado', 'Reservado')], default='disponivel', max_length=10)),
                ('numero_paginas', models.PositiveIntegerField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='livro/')),
                ('fk_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.autor')),
                ('fk_editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.editora')),
            ],
        ),
    ]
